name: django-test-project

services:
  redis:
    container_name: cache_django-test-project
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --loglevel debug

  postgres:
    container_name: postgres_django-test-project
    image: postgres
    ports:
      - '${PG_PORT}:5432'
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB} -p ${PG_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1000k"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
